---
- name: Update packages on Ubuntu
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: Update all packages
      apt: update-cache=yes

    - name: Upgrade all apt packages
      apt: state=latest force_apt_get=yes