---
- name: Stop playbook if Docker is installed on all hosts
  hosts: webservers
  become: yes
  gather_facts: no  # Reduce overhead if facts aren't needed
  tasks:
    - name: Check if Docker is installed on each host
      ansible.builtin.command: which docker
      register: docker_check
      ignore_errors: true

    - name: Mark the host if Docker is not installed
      ansible.builtin.set_fact:
        docker_installed: "{{ docker_check.rc == 0 }}"

- name: Stop playbook if Docker is installed on all hosts
  hosts: webservers
  tasks:
    - name: Check if Docker is installed on all hosts
      ansible.builtin.meta: end_play
      when: >
        not (ansible_play_hosts | map('extract', hostvars, 'docker_installed') | reject('equalto', false) | list | length == 0)

- name: Continue tasks if Docker is not installed everywhere
  hosts: webservers
  tasks:
    - name: Proceed with the play
      ansible.builtin.shell: echo "Docker is not installed on all hosts. Continuing..."

    - name: Update all packages
      apt: update-cache=yes

    - name: Installing required packages
      apt:
        name:
          - "apt-transport-https"
          - "ca-certificates"
          - "curl"
          - "software-properties-common"
        state: present

    - name: Add GPG Key
      ansible.builtin.raw: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"

    - name: Add Docker Repo
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Check docker process post-install
      apt:
        name: docker
        state: present
    
    - name: Add user nish to docker group
      user:
        name: nish
        groups: docker
        append: true

    - name: Pull Docker compose file
      ansible.builtin.raw: 'sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'

    - name: change execute persmissions to docker-compose
      ansible.builtin.raw: "sudo chmod +x /usr/local/bin/docker-compose"